pdflatex MasterDocument.tex
biber MasterDocument
pdflatex MasterDocument.tex
pdflatex MasterDocument.tex
pdflatex MasterPresentation.tex
biber MasterPresentation
pdflatex MasterPresentation.tex
pdflatex MasterPresentation.tex
